#!/bin/bash

export AUTHORIZATION_TOKEN=""
export MY_ORG=""
export PREFIX=""

curl -H "Authorization: token $AUTHORIZATION_TOKEN" \
-s https://api.github.com/search/repositories?q=$PREFIX+in:name+org:$MY_ORG\&per_page=200 \
| perl -ne 'print "$1\n" if (/"ssh_url": "([^"]+)/)' | xargs -n 1 git clone
